
CONFIDENCE_LEVELS = [
    "LOWEST",
    "LOW",
    "MODERATE",
    "HIGH",
    "HIGHEST"
]

ACTIVE_WORD_LIST_SIZE = 5

MCQ_TEST_QUESTION_PER_WORD = 1

INCREASE_CONFIDENCE_ON_CORRECT_MCQ_ANSWER = 1
DECREASE_CONFIDENCE_ON_WRONG_MCQ_ANSWER = 1